-- MySQL Script generated by MySQL Workbench
-- Tue Jun 29 09:38:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fullremote_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullremote_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullremote_db` DEFAULT CHARACTER SET utf8 ;
USE `fullremote_db` ;

-- -----------------------------------------------------
-- Table `fullremote_db`.`Freelancer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullremote_db`.`Freelancer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(80) NOT NULL,
  `speciality` VARCHAR(60) NOT NULL,
  `credit` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullremote_db`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullremote_db`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT now(),
  `language` VARCHAR(45) NOT NULL,
  `Freelancer_sender_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Freelancer_sender_id`),
  INDEX `fk_Message_Freelancer1_idx` (`Freelancer_sender_id` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Freelancer1`
    FOREIGN KEY (`Freelancer_sender_id`)
    REFERENCES `fullremote_db`.`Freelancer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullremote_db`.`Freelancer_has_Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullremote_db`.`Freelancer_has_Message` (
  `Freelancer_recepteur_id` INT NOT NULL,
  `Message_id` INT NOT NULL,
  `acceptation` TINYINT NULL,
  PRIMARY KEY (`Freelancer_recepteur_id`, `Message_id`),
  INDEX `fk_Freelancer_has_Message_Message1_idx` (`Message_id` ASC) VISIBLE,
  INDEX `fk_Freelancer_has_Message_Freelancer_idx` (`Freelancer_recepteur_id` ASC) VISIBLE,
  CONSTRAINT `fk_Freelancer_has_Message_Freelancer`
    FOREIGN KEY (`Freelancer_recepteur_id`)
    REFERENCES `fullremote_db`.`Freelancer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Freelancer_has_Message_Message1`
    FOREIGN KEY (`Message_id`)
    REFERENCES `fullremote_db`.`Message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
